// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zychuiupgxvtdqtzodrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5Y2h1aXVwZ3h2dGRxdHpvZHJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNDQwOTUsImV4cCI6MjA2NDYyMDA5NX0.QA4MJFoUhPmenhYpymsdj8MQSRShcxETwDtkiTnojAk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);